// AUTH 
export const LOGOUT = 'LOGOUT';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export const VERIFIED_USER = 'VERIFIED_USER';

// ERROR MESSAGE
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// CATAN
export const GET_PLAYERS = 'GET_PLAYERS';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';

export const GET_GAME_MODES = 'GET_GAME_MODES';

export const GET_GAME = 'GET_GAME';
export const GET_GAMES = 'GET_GAMES';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';

export const UPDATE_GAME_SUCCESS = 'UPDATE_GAME_SUCCESS';
export const UPDATE_GAME_FAIL = 'UPDATE_GAME_FAIL';

export const DELETE_GAME_SUCCESS = 'DELETE_GAME_SUCCESS';
export const DELETE_GAME_FAIL = 'DELETE_GAME_FAIL';

export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const DELETE_PLAYER_SUCCESS = 'DELETE_PLAYER_SUCCESS';

export const GET_GAME_PLAYERS = 'GET_GAME_PLAYERS';
export const CREATE_GAME_PLAYER = 'CREATE_GAME_PLAYER';
export const UPDATE_GAME_PLAYER = 'UPDATE_GAME_PLAYER';
export const DELETE_GAME_PLAYER = 'DELETE_GAME_PLAYER';

export const GET_GAME_DICE = 'GET_GAME_DICE';
export const CREATE_GAME_DICE = 'CREATE_GAME_DICE';
export const UPDATE_GAME_DICE = 'UPDATE_GAME_DICE';
export const DELETE_GAME_DICE = 'DELETE_GAME_DICE';

export const RESET_FORMS = 'RESET_FORMS';

export const GET_CATAN_STATS = 'GET_CATAN_STATS';